apiVersion: v1
kind: Pod
metadata:
  name: debug-a6000-nrp-01
  namespace: ucsdfutures
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: nrp-01.csumb.edu
  containers:
  - name: debug
    image: nvcr.io/nvidia/pytorch:24.01-py3
    command: ["sleep", "3600"]
    resources:
      requests:
        nvidia.com/rtxa6000: "2"
        memory: "32Gi"
        cpu: "3"
        ephemeral-storage: "50Gi"
      limits:
        nvidia.com/rtxa6000: "2"
        memory: "32Gi"
        cpu: "3"
        ephemeral-storage: "50Gi"
  tolerations:
  - key: "nautilus.io/hardware"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "nvidia.com/rtxa6000"
    operator: "Exists"
    effect: "NoSchedule"
